version: '3'

services:
  database:
    image: mysql:5.7
    restart: always
    container_name: catalyst_case_db
    environment:
      MYSQL_DATABASE: 'catalyst_db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'zxasqw12'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - my-db:/var/lib/mysql
  migration:
    depends_on:
      database:
        condition: service_healthy
    container_name: catalyst_case_migration
    image: catalyst:0.1.0
    command: migrate
  app:
    container_name: catalyst_case_app
    depends_on:
      - database
      - migration        
    ports:
      - '4000:4000'
    expose:
      - '4000'
    image: catalyst:0.1.0
    command: serve

# Names our volume
volumes:
  my-db: